### ISSUE TITLE
Collision issue with specific building

### ISSUE THREAD

**Issue by Art1f1cium** [Flavio514/CarRadSlaughter#3]
Collision gets buggy at about 350 MPH, upon impact, car didn't explode but instead dropped back to 250 MPH

https://user-images.githubusercontent.com/93623782/145321017-6ebfd506-7d40-4bbe-88b6-de4e0f46cf89.mp4

.

**Comment by Flavio514** [comment]
Yes.

**Comment by Flavio514** [comment]
I think that particular building has a bad collision box.
