### ISSUE TITLE
Level needs time to generate upon load

### ISSUE THREAD

**Issue by Flavio514** [Flavio514/CarRadSlaughter#4]
If the level does not load in time (kinda depends on system specs, specifically the CPU and RAM buffering), the player will reach the end of the spawning area and fall into the void. A simple Game Pause followed by a delay and a revert to the Game Pause might do the job.

**Comment by Flavio514** [comment]
A better approach would be to just begin generating the world starting from the player's location, specifically when the game begins. The viability of this approach depends on the world generation implementation.

**Comment by DeathWorld8189** [comment]
I have to check, But I think the endless world module already has a game pause implemented into it that we can enable.

**Comment by DeathWorld8189** [comment]
confirmed, it does
